services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: 
      - path: .env
        required: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./.docker/db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
